version: "3.0"

services:
  node:
    build: .
    ports:
      - "4000:4000"
    command: ["npm", "start"]
    volumes:
      - ./:/usr/src/app
    #   - ./.node_env:/usr/src/app/.env
    links:
      - mongodb

  mongodb:
    image: mongo:4.2.6
    ports:
      - "${MONGO_PORT}:27017"
    command: mongod --auth
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE: "${DBNAME}"
      DBNAME: "${DBNAME}"
      ADMIN_USER: "${ADMIN_USER}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      READ_ONLY_USER: "${READ_ONLY_USER}"
      READ_ONLY_USER_PASSWORD: "${READ_ONLY_USER_PASSWORD}"
  ## minio stacks
